spring.application.name=api-gateway
server.port=8000



#manual routing

spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:8001
spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**


spring.cloud.gateway.routes[2].id=appointment-service
spring.cloud.gateway.routes[2].uri=http://localhost:8002
spring.cloud.gateway.routes[2].predicates[0]=Path=/appointment/**