spring.application.name=api-gateway
server.port=8000



#manual routing

spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:8001
spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**


spring.cloud.gateway.routes[1].id=appointment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8002
spring.cloud.gateway.routes[1].predicates[0]=Path=/appointment/**



eureka.client.service-url.defaultZone=http://localhost:9004/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true